adminUser:
  password: vault:pr-491-5-bdd-frontend/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:pr-491-5-bdd-frontend/pipelineUser:token
  username: cjxd-bot-test
prow:
  hmacToken: vault:pr-491-5-bdd-frontend/prow:hmacToken
